
import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { ThemeProvider } from "@/components/shared/theme-provider";
import DustBackground from "@/components/shared/DustBackground";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
const outfit = Outfit({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.variable}>
    <ThemeProvider
             attribute="class"
             defaultTheme="system"
             enableSystem
             disableTransitionOnChange
             >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        > 
          <DustBackground />
                   <Navbar />
        <Providers>
           {children}
      </Providers>
            <Footer />     
        </body>
             </ThemeProvider>
    </html>
  );
}
